insert into "SYMPHONYC".normal_user (username, last_played_song) values (1, 'zero administration');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (2, 'Re-contextualized');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (3, 'human-resource');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (4, '4th generation');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (5, 'knowledge base');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (6, 'firmware');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (7, 'Sharable');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (8, 'Expanded');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (9, 'stable');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (10, 'homogeneous');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (11, 'productivity');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (12, 'Operative');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (13, 'human-resource');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (14, 'asynchronous');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (15, 'clear-thinking');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (16, 'product');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (17, 'capability');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (18, 'fresh-thinking');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (19, '5th generation');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (20, 'artificial intelligence');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (21, 'workforce');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (22, 'monitoring');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (23, 'forecast');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (24, 'attitude');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (25, 'Polarised');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (26, 'exuding');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (27, 'Optimized');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (28, 'static');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (29, 'protocol');
insert into "SYMPHONYC".normal_user (username, last_played_song) values (30, 'didactic');